var quotes = [
	'I have no idea where this will lead us, but I have a definite feeling it will be a place both wonderful and strange.',
	'One woman can make you fly like an eagle, another can give you the strength of a lion, but only one in the cycle of life can fill your heart with wonder and the wisdom that you have known a singular joy.',
	'Every day, once a day, give yourself a present. Don’t plan it, don’t wait for it, just let it happen.',
	'It was never about the destination. Its always about the journey.',
	'And we will never be alone again Cause it doesn\'t happen everyday.',
	'It\'s like, when you don\'t know someone, they\'re more interesting. They can be anything you want them to be.But when you know them, there\'s limits to them.',
	'Where are you now,Was it all in my fantasy !!,Where are you now,Were you only imaginary !!',
	'Tell me if you wanna go home',
	'I said the wrong thing at the wrong time again but I never really meant',
	'I know you the right one, but maybe we just met at the wrong time.',
	'Fly me to the moon,Let me play among the stars, Let me see what spring is like On a, Jupiter and Mars     In other words, hold my hand',
	'Sitaaron ko aankhon mein mehfuz rakhna,Badi der tak raat hi raat hogi,Musafir hain hum bhi, musafir ho tum bhi, Kisi mod par, phir mulaqat hogi. ~Masaan 🎈🎈',
	'It doesn\'t mean I don\'t care anymore. I don\'t want to let you down, honest, but it just doesn\'t hurt so bad anymore. You can understand that, can\'t you? Please! I need it to be different now. I know I made a promise, but I didn\'t see this coming. I didn\'t count on being happy.Please...tell me that it\'s okay.',
	'**Hedgehog\'s dilemma**The closer we become, the more deeply we hurt each other.',
	'Don\'t lose your way, With each passing day,You\'ve come so far, Don\'t throw it away, Live believing, Dreams are for weaving, Wonders are waiting to startLive your story, Faith, hope and glory,Hold to the truth in your heart',
	'If we hold on together,I know our dreams will never die,Dreams see us through to forever,Where clouds roll by For you and I.',
	'I have to stop beginning with the conclusion. ',
	'It is difficult to get a man to understand something when his salary depends upon his not understanding it.',
	'You are on the path. You don\'t need to know where it leads. Just follow',
	'It doesn\'t matter if we are happy and rest of the world goes to hell.',
	'Friendship is the foundation of any lasting relationship.',
	'You know there\'s one problem with you. You are perfect. ~ Audrey',
	'- Where do you wanna go? - It\'s not really a place. It\'s a feeling.',
	'Beauty too rich for use, for earth too dear.',
	'I seem to be caught in a lifelong rhythm of expecting more from myself than my talent and character can supply.',
	'Everything is known to me, yet somehow beyond my reach.',
	'There are so many things that I don\'t understand,There\'s a world within in me that I cannot explain ,Many rooms to explore but the doors look the same,I am lost I can\'t even remember my name',
	'But now I am not so sure I believe in beginnings and endings.',
	'A tourist in a dream,A visitor it seems,A half-forgotten song,Where do I belong?,Tell me what you see,I need something more.',
	'Hey you, don\'t help them to bury the light; Don\'t give in without a fight Hey you, don\'t tell me there\'s no hope at all; Together we stand, divided we fall',
	'A rainbow, a rainy cloud; Somehow became one, very beautifully;Both wishpered something,;But feelings remain unexpressed',
	'Great players are either far or few.',
	'It might not be the right time;I might not be the right one;But there\'s something about us, I want to say,Cause there\'s something between us anyway',
	'- Can\'t we just let it go ? It wasn\'t hurting anybody.- This thing need to adapt..... Just like rest of us.',
	'Time can stretch and it can squeeze, but, it can’t run backwards! Just can’t. That\'s the worst part of it.',
	'So alive, your touch is like a daylight, Burning on my skin,It turns me on again, You and I,  thought us were the same kind, But we\'re the only ones,Dancing on the sand',
	'Your brain is who you are.',
	'In your eyes, I see something to believe in, Your hands are like a flame, Your palms the sweetest pain.',
	'I grew a flower that can\'t be bloomed in a dream that can\'t come true.',
	'- So, how are you today ? - Weird, actually.',
	'Everything you do in life is to distract you from yourself',
	'I would love to see the world through your eyes.',
	'Time heals all wounds. Believe me',
	'I wish love was perfect as love itself.',
	'I drifted alone, in the ocean of life; But then you pulled me, dear, from the waters of strife.',
	'You\'re in the water, I\'m standing on the shore, Still thinking that I hear your voice.',
	'- Some people think I am strange. - I know the feeling.',
	'Shadow Take Me Down; Shadow Take Me Down; Shadow Take Me Down ; For The Last Time',
	'I took your picture from the frame; And now you\'re nothing like you seem; Your shadow fell like last night\'s rain',
	'Summer days are growing colder; We\'ll know better when we\'re older',
	'It\'s loneliest feeling to know who you really are.',
	'You\'ll always be a part of me;You gave me a song to sing.',
	'So give me reason, To prove me wrong.',
	'There something inside you, It\'s hard to explain, They\'re talking about you boy, But you\'re still the same',
	'- Someone must have hurt you once really badly. - No, someone was hurt by me. And I will never let that happen again.',
	'Nothing ever changes here, I know; Another day, another year, same old; I don\'t wanna live my life in circles, I just wanna find an empty road.',
	'We are like the dreamer who dreams and lives inside the dream, but who is the dreamer?',
	'Jerry : Women, they\'re so subtle, their little...everything they do is subtle...men are not subtle, we are obvious. Women know what men want, men know what men want, what do we want? We want women, that\'s it!...'
]

function newQuote() {
	var randomNumber = Math.floor(Math.random()* quotes.length);
	document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
